{{- if not .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "callosum.secretName" . }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.auth.secrets }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}