{{- if gt (int .Values.celery_worker_docfetching.replicaCount) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "callosum.fullname" . }}-celery-worker-docfetching
  labels:
    {{- include "callosum.labels" . | nindent 4 }}
    {{- with .Values.celery_worker_docfetching.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.celery_worker_docfetching.autoscaling.enabled }}
  replicas: {{ .Values.celery_worker_docfetching.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "callosum.selectorLabels" . | nindent 6 }}
      {{- if .Values.celery_worker_docfetching.deploymentLabels }}
      {{- toYaml .Values.celery_worker_docfetching.deploymentLabels | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.celery_worker_docfetching.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "callosum.labels" . | nindent 8 }}
        {{- with .Values.celery_worker_docfetching.deploymentLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.celery_worker_docfetching.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "callosum.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.celery_shared.podSecurityContext | nindent 8 }}
      {{- with .Values.celery_worker_docfetching.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celery_worker_docfetching.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celery_worker_docfetching.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: celery-worker-docfetching
          securityContext:
            {{- toYaml .Values.celery_shared.securityContext | nindent 12 }}
          image: "{{ .Values.celery_shared.image.repository }}:{{ .Values.celery_shared.image.tag | default .Values.global.version }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command:
            [
              "celery",
              "-A",
              "callosum.background.celery.versioned_apps.docfetching",
              "worker",
              "--pool=threads",
              "--concurrency=2",
              "--prefetch-multiplier=1",
              "--loglevel=INFO",
              "--hostname=docfetching@%n",
              "-Q",
              "connector_doc_fetching,user_files_indexing",
            ]
          resources:
            {{- toYaml .Values.celery_worker_docfetching.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.envConfigMapName }}
          env:
            {{- include "callosum.envSecrets" . | nindent 12}}
          {{- with .Values.celery_worker_docfetching.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            {{ .Values.celery_shared.startupProbe | toYaml | nindent 12}}
          readinessProbe:
            {{ .Values.celery_shared.readinessProbe | toYaml | nindent 12}}
            exec:
              command:
                - /bin/bash
                - -c
                - >
                    python callosum/background/celery/celery_k8s_probe.py
                    --probe readiness
                    --filename /tmp/callosum_k8s_docfetching_readiness.txt
          livenessProbe:
            {{ .Values.celery_shared.livenessProbe | toYaml | nindent 12}}
            exec:
              command:
                - /bin/bash
                - -c
                - >
                    python callosum/background/celery/celery_k8s_probe.py
                    --probe liveness
                    --filename /tmp/callosum_k8s_docfetching_liveness.txt
      {{- with .Values.celery_worker_docfetching.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
