apiVersion: v1
kind: Service
metadata:
  name: {{ include "callosum.fullname" . }}-webserver
  labels:
    {{- include "callosum.labels" . | nindent 4 }}
    {{- if .Values.webserver.deploymentLabels }}
    {{- toYaml .Values.webserver.deploymentLabels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
    - port: {{ .Values.webserver.service.servicePort }}
      targetPort: {{ .Values.webserver.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "callosum.selectorLabels" . | nindent 4 }}
    {{- if .Values.webserver.deploymentLabels }}
    {{- toYaml .Values.webserver.deploymentLabels | nindent 4 }}
    {{- end }}
